const colorCombs = {
  GG: "G",
  BR: "G",
  RB: "G",
  RR: "R",
  GB: "R",
  BG: "R",
  BB: "B",
  GR: "B",
  RG: "B",
};

function triangle(row) {
  if (row.length === 1) return row;

  let nextRow = [];

  for (let i = 0; i < row.length - 1; i++) {
    let currentColorComb = `${row[i]}${row[i + 1]}`;
    nextRow.push(colorCombs[currentColorComb]);
  }

  return triangle(nextRow.join(""));
}

// DESCRIPTION:
// Disclaimer
// This Kata is an insane step-up from Avanta's Kata, so I recommend to solve it first before trying this one.

// Problem Description
// A coloured triangle is created from a row of colours, each of which is red, green or blue. Successive rows, each containing one fewer colour than the last, are generated by considering the two touching colours in the previous row. If these colours are identical, the same colour is used in the new row. If they are different, the missing colour is used in the new row. This is continued until the final row, with only a single colour, is generated.

// For example, different possibilities are:

// Colour here:            G G        B G        R G        B R
// Becomes colour here:     G          R          B          G
// With a bigger example:

// R R G B R G B B
//  R B R G B R B
//   G G B R G G
//    G R G B G
//     B B R R
//      B G R
//       R B
//        G
// You will be given the first row of the triangle as a string and its your job to return the final colour which would appear in the bottom row as a string. In the case of the example above, you would be given 'RRGBRGBB', and you should return 'G'.

// Constraints
// 1 <= length(row) <= 10 ** 5

// The input string will only contain the uppercase letters 'B', 'G' or 'R'.

// The exact number of test cases will be as follows:

// 100 tests of 100 <= length(row) <= 1000
// 100 tests of 1000 <= length(row) <= 10000
// 100 tests of 10000 <= length(row) <= 100000
// Examples

console.log("triangle('B') should give:");
console.log("B");
console.log(`It gives: ${triangle("B")}`);
console.log("----------------------------------------");

console.log("triangle('GB') should give:");
console.log("R");
console.log(`It gives: ${triangle("GB")}`);
console.log("----------------------------------------");

console.log("triangle('RRR') should give:");
console.log("R");
console.log(`It gives: ${triangle("RRR")}`);
console.log("----------------------------------------");

console.log("triangle('RGBG') should give:");
console.log("B");
console.log(`It gives: ${triangle("RGBG")}`);
console.log("----------------------------------------");

console.log("triangle('RBRGBRB') should give:");
console.log("G");
console.log(`It gives: ${triangle("RBRGBRB")}`);
console.log("----------------------------------------");

console.log("triangle('RBRGBRBGGRRRBGBBBGG') should give:");
console.log("G");
console.log(`It gives: ${triangle("RBRGBRBGGRRRBGBBBGG")}`);
console.log("----------------------------------------");
